# Generated by Django 4.0.10 on 2023-09-27 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_basemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseModel',
        ),
    ]
